- name: try to find and to send public ssh key to host
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  register: find_public_ssh_key
  ignore_errors: yes
  
- name: creat ssh keys on localhost
  become: false
  local_action: command ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
  when: find_public_ssh_key is failed

- name: send public ssh key to host again
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  when: find_public_ssh_key is failed
