- name: ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - python3-pip
      - libssl-dev
      - python3-venv
    state: present
    
- name: Check the path for Python
  ansible.builtin.command: which python3
  register: python_interpreter_path
   
- name: Ensure molecule is installed in a virtual environment
  ansible.builtin.pip:
   name: molecule
   version: ""
   state: present
   virtualenv: "{{ molecule_install_virtualenv }}"
   virtualenv_command: "{{ python_interpreter_path.stdout }} -m venv"  

- name: Ensure molecule support packages are installed in a virtual environment
  ansible.builtin.pip:
    name: "molecule[{{ item }}]"
    version: ""
    state: present
    virtualenv: "{{ molecule_install_virtualenv }}"
    virtualenv_command: "{{ python_interpreter_path.stdout }} -m venv"    
  with_items: "{{ molecule_install_list }}"
