- name: include ssh_actions_add_public_key_to_host
  include_tasks: ./tasks/actions/ssh_actions_add_public_key_to_host.yml
  when: ssh_actions_add_public_key_to_host

- name: include ssh_actions_no_password_for_sudo
  include_tasks: ./tasks/actions/ssh_actions_no_password_for_sudo.yml
  when:
    - ssh_actions_no_password_for_sudo
    - ansible_user != "root"
