- name: add no password group
  ansible.builtin.group:
    name: "sudo_password_disable"
    state: present

- name: creat file sudo_password_disable in sudoers.d
  ansible.builtin.copy:
    content: '%sudo_password_disable ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/sudo_password_disable
    owner: "root"
    mode: 0440

- name: add ansible user to sudo_password_disable
  ansible.builtin.user:
   name: "{{ ansible_user }}"
   group: "sudo_password_disable"
